//+------------------------------------------------------------------+
//|                                   Enhanced ChartDrawing.mqh      |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, MetaQuotes Ltd."
#property link      "https://www.mql5.com"

#define CONFIDENCE_PREFIX      "PredictEA_Conf_"
#define INFO_PANEL_PREFIX      "PredictEA_Info_"
#define ACCURACY_PREFIX        "PredictEA_Acc_"
#define HOURLY_X_COORD         15
#define DAILY_X_COORD          350
#define START_Y_COORD          80
#define Y_SPACING              30
#define MAX_PREDICTIONS        5
#define PANEL_WIDTH            180
#define PANEL_HEIGHT           25

struct PredictionAccuracy{datetime targetTime;double predictedPrice;double actualPrice;double accuracy;bool completed;};
class CChartDrawing
{
private:
    long chartId;double currentHourlyPredictions[MAX_PREDICTIONS];double currentDailyPredictions[MAX_PREDICTIONS];datetime lastHourlyUpdate;datetime lastDailyUpdate;bool forceNextUpdate;PredictionAccuracy hourlyAccuracy[MAX_PREDICTIONS][100];PredictionAccuracy dailyAccuracy[MAX_PREDICTIONS][50];int hourlyAccuracyCount[MAX_PREDICTIONS];int dailyAccuracyCount[MAX_PREDICTIONS];double hourlyRunningAccuracy[MAX_PREDICTIONS];double dailyRunningAccuracy[MAX_PREDICTIONS];
public:
    CChartDrawing();~CChartDrawing();bool Initialize(long chartID=0);bool UpdatePredictions(double &hourlyPreds[],double &dailyPreds[]);bool ShouldUpdateHourly();bool ShouldUpdateDaily();void DrawPredictionLists();void UpdateAccuracyTracking();bool UpdateConfidenceIndicator(double confidence);void HandleChartEvent(int id,long lparam,double dparam,string sparam);void Cleanup();void ForceUpdate();
private:
    bool CreateRectangleLabel(string n,int x,int y,int w,int h,color c,color b=clrNONE);bool CreateTextLabel(string n,int x,int y,string t,color c,int f=9);void RemoveObjectsByPrefix(string prefix);string GenerateObjectName(string prefix,int index);double CalculateAccuracy(double predicted,double actual);void UpdateRunningAccuracy(int pIndex,bool isHourly);color GetAccuracyColor(double accuracy);datetime GetCurrentHourStart();datetime GetCurrentDayStart();void StorePredictionForAccuracy(int index,double prediction,bool isHourly);void CheckCompletedPredictions();
};
CChartDrawing::CChartDrawing(){chartId=0;lastHourlyUpdate=0;lastDailyUpdate=0;forceNextUpdate=false;ArrayInitialize(currentHourlyPredictions,0.0);ArrayInitialize(currentDailyPredictions,0.0);ArrayInitialize(hourlyAccuracyCount,0);ArrayInitialize(dailyAccuracyCount,0);ArrayInitialize(hourlyRunningAccuracy,0.0);ArrayInitialize(dailyRunningAccuracy,0.0);}
CChartDrawing::~CChartDrawing(){Cleanup();}
bool CChartDrawing::Initialize(long chartID){chartId=(chartID==0)?ChartID():chartID;if(chartId==-1)return false;DrawPredictionLists();return true;}
void CChartDrawing::ForceUpdate(){forceNextUpdate=true;}
datetime CChartDrawing::GetCurrentHourStart(){MqlDateTime dt;TimeToStruct(TimeCurrent(),dt);dt.min=0;dt.sec=0;return StructToTime(dt);}
datetime CChartDrawing::GetCurrentDayStart(){MqlDateTime dt;TimeToStruct(TimeCurrent(),dt);dt.hour=0;dt.min=0;dt.sec=0;return StructToTime(dt);}
bool CChartDrawing::ShouldUpdateHourly(){if(forceNextUpdate)return true;return(lastHourlyUpdate<GetCurrentHourStart());}
bool CChartDrawing::ShouldUpdateDaily(){if(forceNextUpdate)return true;return(lastDailyUpdate<GetCurrentDayStart());}
bool CChartDrawing::UpdatePredictions(double &hourlyPreds[],double &dailyPreds[]){bool updated=false;if(ShouldUpdateHourly()&&ArraySize(hourlyPreds)>=MAX_PREDICTIONS){CheckCompletedPredictions();for(int i=0;i<MAX_PREDICTIONS;i++){currentHourlyPredictions[i]=hourlyPreds[i];StorePredictionForAccuracy(i,hourlyPreds[i],true);}lastHourlyUpdate=TimeCurrent();updated=true;}if(ShouldUpdateDaily()&&ArraySize(dailyPreds)>=MAX_PREDICTIONS){for(int i=0;i<MAX_PREDICTIONS;i++){currentDailyPredictions[i]=dailyPreds[i];StorePredictionForAccuracy(i,dailyPreds[i],false);}lastDailyUpdate=TimeCurrent();updated=true;}if(forceNextUpdate&&updated){forceNextUpdate=false;}DrawPredictionLists();UpdateAccuracyTracking();return updated;}
void CChartDrawing::DrawPredictionLists(){RemoveObjectsByPrefix("PredictEA_");double p=SymbolInfoDouble(_Symbol,SYMBOL_BID);(GenerateObjectName("PredictEA_HList_Header",0),HOURLY_X_COORD,START_Y_COORD-25,"HOURLY PREDICTIONS",clrWhite,11);CreateTextLabel(GenerateObjectName("PredictEA_DList_Header",0),DAILY_X_COORD,START_Y_COORD-25,"DAILY PREDICTIONS",clrWhite,11);for(int i=0;i<MAX_PREDICTIONS;i++){int y=START_Y_COORD+(i*Y_SPACING);CreateRectangleLabel(GenerateObjectName("PredictEA_HList_Bg_",i),HOURLY_X_COORD-5,y-2,PANEL_WIDTH,PANEL_HEIGHT,clrDarkSlateGray,clrGray);string hTxt="H"+(string)(i+1)+": "+(currentHourlyPredictions[i]>0?DoubleToString(currentHourlyPredictions[i],_Digits):"Waiting...");color hClr=(currentHourlyPredictions[i]>0)?(currentHourlyPredictions[i]>p?clrLimeGreen:clrTomato):clrGray;CreateTextLabel(GenerateObjectName("PredictEA_HList_Text_",i),HOURLY_X_COORD+5,y+6,hTxt,hClr,9);int h_c=0;for(int j=0;j<MathMin(100,hourlyAccuracyCount[i]);j++)if(hourlyAccuracy[i][j].completed)h_c++;if(h_c>0){string aTxt=DoubleToString(hourlyRunningAccuracy[i],1)+"% ("+(string)h_c+")";CreateTextLabel(GenerateObjectName(ACCURACY_PREFIX+"H_",i),HOURLY_X_COORD+100,y+6,aTxt,GetAccuracyColor(hourlyRunningAccuracy[i]),8);}CreateRectangleLabel(GenerateObjectName("PredictEA_DList_Bg_",i),DAILY_X_COORD-5,y-2,PANEL_WIDTH,PANEL_HEIGHT,clrDarkSlateGray,clrGray);string dTxt="D"+(string)(i+1)+": "+(currentDailyPredictions[i]>0?DoubleToString(currentDailyPredictions[i],_Digits):"Waiting...");color dClr=(currentDailyPredictions[i]>0)?(currentDailyPredictions[i]>p?clrLimeGreen:clrTomato):clrGray;CreateTextLabel(GenerateObjectName("PredictEA_DList_Text_",i),DAILY_X_COORD+5,y+6,dTxt,dClr,9);int d_c=0;for(int j=0;j<MathMin(50,dailyAccuracyCount[i]);j++)if(dailyAccuracy[i][j].completed)d_c++;if(d_c>0){string aTxt=DoubleToString(dailyRunningAccuracy[i],1)+"% ("+(string)d_c+")";CreateTextLabel(GenerateObjectName(ACCURACY_PREFIX+"D_",i),DAILY_X_COORD+100,y+6,aTxt,GetAccuracyColor(dailyRunningAccuracy[i]),8);}}string uTxt="Last Updates: H="+TimeToString(lastHourlyUpdate,TIME_MINUTES)+" D="+TimeToString(lastDailyUpdate,TIME_DATE|TIME_MINUTES);CreateTextLabel(GenerateObjectName(INFO_PANEL_PREFIX+"Updates",0),HOURLY_X_COORD,START_Y_COORD+(MAX_PREDICTIONS*Y_SPACING)+10,uTxt,clrYellow,8);ChartRedraw(chartId);}
void CChartDrawing::StorePredictionForAccuracy(int index,double prediction,bool isHourly){if(index<0||index>=MAX_PREDICTIONS)return;if(isHourly){int s=hourlyAccuracyCount[index]%100;hourlyAccuracy[index][s].targetTime=GetCurrentHourStart()+((index+1)*3600);hourlyAccuracy[index][s].predictedPrice=prediction;hourlyAccuracy[index][s].completed=false;hourlyAccuracyCount[index]++;}else{int s=dailyAccuracyCount[index]%50;dailyAccuracy[index][s].targetTime=GetCurrentDayStart()+((index+1)*86400);dailyAccuracy[index][s].predictedPrice=prediction;dailyAccuracy[index][s].completed=false;dailyAccuracyCount[index]++;}}
void CChartDrawing::CheckCompletedPredictions(){datetime t=TimeCurrent();for(int i=0;i<MAX_PREDICTIONS;i++){int h_l=MathMin(hourlyAccuracyCount[i],100);for(int j=0;j<h_l;j++){if(!hourlyAccuracy[i][j].completed&&t>=hourlyAccuracy[i][j].targetTime){MqlRates r[];if(CopyRates(_Symbol,PERIOD_H1,hourlyAccuracy[i][j].targetTime,1,r)>0){hourlyAccuracy[i][j].actualPrice=r[0].close;hourlyAccuracy[i][j].accuracy=CalculateAccuracy(hourlyAccuracy[i][j].predictedPrice,r[0].close);hourlyAccuracy[i][j].completed=true;UpdateRunningAccuracy(i,true);}}}int d_l=MathMin(dailyAccuracyCount[i],50);for(int j=0;j<d_l;j++){if(!dailyAccuracy[i][j].completed&&t>=dailyAccuracy[i][j].targetTime){MqlRates r[];if(CopyRates(_Symbol,PERIOD_D1,dailyAccuracy[i][j].targetTime,1,r)>0){dailyAccuracy[i][j].actualPrice=r[0].close;dailyAccuracy[i][j].accuracy=CalculateAccuracy(dailyAccuracy[i][j].predictedPrice,r[0].close);dailyAccuracy[i][j].completed=true;UpdateRunningAccuracy(i,false);}}}}}
double CChartDrawing::CalculateAccuracy(double predicted,double actual){if(actual==0)return 0.0;double a=(1.0-MathAbs(predicted-actual)/actual)*100.0;return MathMax(0.0,MathMin(100.0,a));}
void CChartDrawing::UpdateRunningAccuracy(int pIndex,bool isHourly){if(pIndex<0||pIndex>=MAX_PREDICTIONS)return;double total=0.0;int count=0;if(isHourly){int l=MathMin(hourlyAccuracyCount[pIndex],100);for(int i=0;i<l;i++){if(hourlyAccuracy[pIndex][i].completed){total+=hourlyAccuracy[pIndex][i].accuracy;count++;}}if(count>0)hourlyRunningAccuracy[pIndex]=total/count;}else{int l=MathMin(dailyAccuracyCount[pIndex],50);for(int i=0;i<l;i++){if(dailyAccuracy[pIndex][i].completed){total+=dailyAccuracy[pIndex][i].accuracy;count++;}}if(count>0)dailyRunningAccuracy[pIndex]=total/count;}}
color CChartDrawing::GetAccuracyColor(double a){if(a>=80.0)return clrLimeGreen;if(a>=65.0)return clrYellow;if(a>=50.0)return clrOrange;return clrRed;}
void CChartDrawing::UpdateAccuracyTracking(){CheckCompletedPredictions();}
bool CChartDrawing::UpdateConfidenceIndicator(double c){RemoveObjectsByPrefix(CONFIDENCE_PREFIX);int x=220,y=20,w=200,h=25;CreateRectangleLabel(GenerateObjectName(CONFIDENCE_PREFIX+"Bg",0),x-5,y-5,w+10,h+10,clrDarkSlateGray,clrGray);color clr=(c>=0.8)?clrLimeGreen:(c>=0.6)?clrYellow:clrOrange;CreateRectangleLabel(GenerateObjectName(CONFIDENCE_PREFIX+"Bar",0),x,y,(int)(w*c),h,clr);CreateTextLabel(GenerateObjectName(CONFIDENCE_PREFIX+"Text",0),x+10,y+6,"NN Confidence: "+DoubleToString(c*100,1)+"%",clrWhite,10);ChartRedraw(chartId);return true;}
bool CChartDrawing::CreateRectangleLabel(string n,int x,int y,int w,int h,color c,color b){if(!ObjectCreate(chartId,n,OBJ_RECTANGLE_LABEL,0,0,0))return false;ObjectSetInteger(chartId,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(chartId,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(chartId,n,OBJPROP_XSIZE,w);ObjectSetInteger(chartId,n,OBJPROP_YSIZE,h);ObjectSetInteger(chartId,n,OBJPROP_BGCOLOR,c);ObjectSetInteger(chartId,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(chartId,n,OBJPROP_BACK,true);ObjectSetInteger(chartId,n,OBJPROP_SELECTABLE,true);if(b!=clrNONE)ObjectSetInteger(chartId,n,OBJPROP_COLOR,b);return true;}
bool CChartDrawing::CreateTextLabel(string n,int x,int y,string t,color c,int f){if(!ObjectCreate(chartId,n,OBJ_LABEL,0,0,0))return false;ObjectSetInteger(chartId,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(chartId,n,OBJPROP_YDISTANCE,y);ObjectSetString(chartId,n,OBJPROP_TEXT,t);ObjectSetInteger(chartId,n,OBJPROP_COLOR,c);ObjectSetInteger(chartId,n,OBJPROP_FONTSIZE,f);ObjectSetString(chartId,n,OBJPROP_FONT,"Arial Bold");ObjectSetInteger(chartId,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(chartId,n,OBJPROP_BACK,false);ObjectSetInteger(chartId,n,OBJPROP_SELECTABLE,true);return true;}
void CChartDrawing::RemoveObjectsByPrefix(string prefix){for(int i=ObjectsTotal(chartId)-1;i>=0;i--){if(StringFind(ObjectName(chartId,i),prefix)==0)ObjectDelete(chartId,ObjectName(chartId,i));}}
string CChartDrawing::GenerateObjectName(string prefix,int index){return prefix+(string)index+"_"+(string)GetMicrosecondCount();}
void CChartDrawing::HandleChartEvent(int id,long lparam,double dparam,string sparam){}
void CChartDrawing::Cleanup(){RemoveObjectsByPrefix("PredictEA_");ChartRedraw(chartId);}